const types = {
  SET_SELECTED_SUBREDDIT: 'SET_SELECTED_SUBREDDIT',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  CLEAR_STATE: 'CLEAR_STATE',
  SET_POSTS: 'SET_POSTS',
  GET_POSTS: 'GET_POSTS',
  GET_FILTERED_POSTS: 'GET_FILTERED_POSTS',
};

export default types;
